from importlib.metadata import PackageNotFoundError, version

from perp_md.capabilities import (
    COVERAGE_SCHEMA_VERSION,
    DECLARED_COVERAGE_SCHEMA_ID,
    MANIFEST_ID,
    AcquisitionPlan,
    AdapterManifest,
    CapabilityAlternative,
    CapabilityAssessment,
    CapabilityDeclaration,
    CapabilityIssue,
    CapabilityRequirements,
    CapabilityStatus,
    DeclaredState,
    HistoryScope,
    NativeName,
    NativeProductMapping,
    PaginationMode,
    PlannedRetrieval,
    RequestScope,
    RetrievalDeclaration,
    assess_capability,
    builtin_manifests,
    coverage_manifest,
    coverage_manifest_json,
    instrument_descriptor_from_instrument,
    load_coverage_schema,
)
from perp_md.client import OpenInterestClient
from perp_md.errors import (
    AdapterUnavailable,
    CapabilityUnavailable,
    DataUnavailable,
    FundingObservationDecodeError,
    InvalidInstrument,
    InvalidResponse,
    NativeIdentityResolutionError,
    PaginationError,
    PerpMdError,
    RequestError,
)
from perp_md.funding_client import FundingClient
from perp_md.funding_wire import (
    FUNDING_OBSERVATION_SCHEMA_ID,
    funding_observation_from_data,
    funding_observation_from_json,
    funding_observation_to_data,
    funding_observation_to_json,
    load_funding_observation_schema,
)
from perp_md.history import find_resume_time
from perp_md.models import (
    ContractDirection,
    FundingCapabilities,
    FundingObservation,
    FundingResult,
    HistoryIssue,
    HistoryRange,
    Instrument,
    NativeUnit,
    ObservationTimeKind,
    OpenInterestCapabilities,
    OpenInterestObservation,
    OpenInterestResult,
    ProviderFundingEvidence,
    ValuationMethod,
)

try:
    __version__ = version("perp-md")
except PackageNotFoundError:
    __version__ = "0.0.0+uninstalled"

__all__ = [
    "AcquisitionPlan",
    "AdapterManifest",
    "AdapterUnavailable",
    "CapabilityAlternative",
    "CapabilityAssessment",
    "CapabilityDeclaration",
    "CapabilityIssue",
    "CapabilityRequirements",
    "CapabilityStatus",
    "CapabilityUnavailable",
    "COVERAGE_SCHEMA_VERSION",
    "ContractDirection",
    "DataUnavailable",
    "DECLARED_COVERAGE_SCHEMA_ID",
    "DeclaredState",
    "FUNDING_OBSERVATION_SCHEMA_ID",
    "FundingCapabilities",
    "FundingClient",
    "FundingObservation",
    "FundingObservationDecodeError",
    "FundingResult",
    "HistoryIssue",
    "HistoryRange",
    "HistoryScope",
    "Instrument",
    "InvalidInstrument",
    "InvalidResponse",
    "MANIFEST_ID",
    "NativeName",
    "NativeIdentityResolutionError",
    "NativeProductMapping",
    "NativeUnit",
    "ObservationTimeKind",
    "OpenInterestCapabilities",
    "OpenInterestClient",
    "OpenInterestObservation",
    "OpenInterestResult",
    "PaginationError",
    "PaginationMode",
    "PlannedRetrieval",
    "PerpMdError",
    "ProviderFundingEvidence",
    "RequestError",
    "RequestScope",
    "RetrievalDeclaration",
    "ValuationMethod",
    "assess_capability",
    "builtin_manifests",
    "coverage_manifest",
    "coverage_manifest_json",
    "find_resume_time",
    "funding_observation_from_data",
    "funding_observation_from_json",
    "funding_observation_to_data",
    "funding_observation_to_json",
    "instrument_descriptor_from_instrument",
    "load_coverage_schema",
    "load_funding_observation_schema",
]
